services:
  postgres:
    image: postgres:15.7
    environment:
      POSTGRES_PASSWORD: PostgresR00t
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge
